FROM node:alpine
RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH


COPY ./package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.1 -g --silent

CMD ["npm", "start"]